caption: Enable automated password change
desc: |-
  This policy controls the availability of <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph>'s automated password change feature.

  If enabled, a user can trigger a process where the browser attempts to change their password on a website automatically. This process is managed by Generative AI. The new password is saved in the browser's password manager.

  0 = Allow the feature to be used, while allowing Google to use relevant data to improve its AI models. Relevant data may include prompts, inputs, outputs, source materials, and written feedback, depending on the feature. It may also be reviewed by humans to improve AI models. 0 is the default value, except when noted below.

  1 = Allow the feature to be used, but does not allow Google to improve models using users' content (including prompts, inputs, outputs, source materials, and written feedback). 1 is the default value for Enterprise users managed by Google Admin console and for Education accounts managed by Google Workspace.

  2 = Do not allow the feature.

  If the policy is unset, its behavior is determined by the GenAiDefaultSettings policy.

  For more information on data handling for generative AI features, please see https://support.google.com/chrome/a?p=generative_ai_settings.

default: 0
example_value: 1
features:
  dynamic_refresh: true
  per_profile: true
items:
- caption: Allow feature use and improving AI models
  name: Allowed
  value: 0
- caption: Allow feature use without improving AI models
  name: AllowedWithoutLogging
  value: 1
- caption: Do not allow feature
  name: Disabled
  value: 2
owners:
- file://components/password_manager/OWNERS
schema:
  enum:
  - 0
  - 1
  - 2
  type: integer
tags:
- google-sharing
supported_on:
- chrome.*:140-
- chrome_os:140-
tags: []
type: int-enum

