# See https://jj-vcs.github.io/jj/latest/config/ for the schema.

[aliases]
# cr-* aliases are the equivalent of "porcelain" commands and should not
# be overridden.
# All cr-foo commands will have a corresponding foo command that you can
# override with your preference (eg. sync -> ["cr-sync", "-a"])
"cr-sync" = ["util", "exec", "tools/jj/sync.py", "--"]
"sync" = ["cr-sync"]

[revset-aliases]
"trunk()" = "main@origin"
"immutable_heads()" = "remote_bookmarks() | tags()"

[git]
auto-local-bookmark = false
# This is unrelated to gerrit change IDs.
# It will eventually be supported by gerrit instead of the Change-ID footer.
write-change-id-header = true

[templates]
# This is a little awkward to use during `jj split` operations.
# Two commits will share the same gerrit change-ID
# We should be able to remove this once gerrit supports git headers.
# See https://github.com/jj-vcs/jj/issues/4387#issuecomment-2865171741
commit_trailers = '''
if(!trailers.contains_key("Change-Id"), format_gerrit_change_id_trailer(self))
'''

# For users of jj-on-piper, this is enabled by default for *all* repos.
# We want chrome's formatters, not google3's.
[fix.tools.google3format]
enabled = false

# The source of truth for the following formatters is depot_tools' git_cl.py
[fix.tools.gn-format]
command = ["gn", "format", "--stdin"]
patterns = [
    "glob:'**/*.gn'",
    "glob:'**/*.gni'",
    "glob:'**/*.typemap'",
]

[fix.tools.java-format]
command = ["third_party/google-java-format/google-java-format", "--aosp", "-"]
patterns = ["glob:'**/*.java'"]

[fix.tools.rust-format]
command = ["third_party/depot_tools/rustfmt.py", "--config-path=.rustfmt.toml"]
patterns = ["glob:'**/*.rs'"]

[fix.tools.clang-format]
command = ["third_party/depot_tools/clang_format.py", "--assume-filename=$path"]
patterns = [
    "glob:'**/*.cc'",
    "glob:'**/*.cpp'",
    "glob:'**/*.h'",
    "glob:'**/*.m'",
    "glob:'**/*.mm'",
    "glob:'**/*.proto'",
    "glob:'**/*.js'",
    "glob:'**/*.ts'",
]

[fix.tools.py-format]
command = ["tools/jj/formatters/python.py", "$path"]
patterns = ["glob:'**/*.py'"]

[fix.tools.swift-format]
command = ["tools/jj/formatters/swift.py", "format"]
patterns = ["glob:'**/*.swift'"]

[fix.tools.mojom-format]
command = ["vpython3", "mojo/public/tools/mojom/mojom_format.py"]
patterns = [
    "glob:'**/*.mojom'",
    "glob:'**/*.test-mojom'",
]

[fix.tools.lucicfg-format]
command = ["lucicfg", "fmt", "-stdio", "$path"]
patterns = ["glob:'**/*.star'"]
